steps:
  #### STAGE ####
  - label: ":docker: Build Project"
    plugins:
    - docker#v3.9.0:
          image: "golang:1.18.0"
          workdir: "/app"
          volumes:
            - ".:/app"
    command:
      - go build -o hello/hello ./hello
    artifact_paths:
      - "hello/hello"
  #### STAGE ####
  - label: ":question: Enter Name"
    type: block
    prompt: "What is your name?"
    fields:
      - text: "Enter your name here"
        key: "name"
  #### STAGE ####
  - block: "Request Release"
    fields:
      - select: "Stream"
        key: "release-stream"
        options:
          - label: "Beta"
            value: "beta"
          - label: "Stable"
            value: "stable"
    #### STAGE ####
  - label: ":large_green_circle: Running Hello Go program"
    command:
      - buildkite-agent artifact download "hello/hello" .
      - chmod +x hello/hello
      - ./hello/hello $(buildkite-agent meta-data get "name")
