steps:
  #### STAGE ####
  - label: ":docker: Build Project"
    plugins:
    - docker#v3.9.0:
          image: "golang:1.18.0"
          workdir: "/app"
          volumes:
            - ".:/app"
    command:
      - go build -o hello/hello ./hello
    artifact_paths:
      - "hello/hello"
  #### STAGE ####
  - label: ":question: Enter Name"
    type: block
    prompt: "What is your name?"
    fields:
      - text: "Enter your name here"
        key: "name"
        default: "Bob Saget"
  #### STAGE ####
  - block: "Manager Approval"
    fields:
      - select: "Do you approve of the build?"
        key: "choice"
        options:
          - label: "Yes"
            value: "yes"
          - label: "No"
            value: "no"
  
  - label: "Load release type into env variable"
    command: 
    - choice=$(buildkite-agent meta-data get "choice")
    - echo $choice
    
    #### STAGE ####
  - label: ":large_green_circle: Running Hello Go program"
    #depends on: "choice"
    command:
      #- buildkite-agent artifact download "hello/hello" .
      #- chmod +x hello/hello
      #- ./hello/hello $(buildkite-agent meta-data get "name")
      - chmod +x script.sh
      - ./script.sh
